"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, Bike, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileCheck2, History, IdCard,
  LoaderCircle, MapPin, Navigation, PackageCheck, Phone, Play, RefreshCw, ShieldCheck, Upload, UserRound, WalletCards, X
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { PortalShell } from "@/components/portal-shell";
import { AuthGate } from "@/components/auth-gate";
import { Badge, Button, Card, EmptyState, Modal, PageHeader, SectionCard, StatusBadge } from "@/components/ui";
import { useAuth } from "@/components/firebase-provider";
import { useToast } from "@/components/providers";
import { authenticatedFetch } from "@/lib/api-client";
import { uploadFile } from "@/lib/firebase-services";
import { formatCurrency } from "@/lib/format";
import { cn } from "@/lib/cn";
import { NotificationCenter } from "@/components/notification-center";

const sectionMeta = {
  home: { title: "Driver home", description: "Your shift, live availability and next delivery action." },
  jobs: { title: "Available deliveries", description: "See the route and guaranteed pay before you accept." },
  active: { title: "Active delivery", description: "Complete one clear step at a time." },
  earnings: { title: "Earnings", description: "Your delivery earnings and payout history." },
  history: { title: "Delivery history", description: "Completed and previous delivery work." },
  notifications: { title: "Driver notifications", description: "Application reviews, delivery offers, payouts and Driver account activity." },
  support: { title: "Safety and support", description: "Report a problem with the current delivery or your Driver account." },
  profile: { title: "Driver account", description: "Your approval, vehicle, documents and payout setup." }
};

const APPLICATION_STEPS = ["Your details", "Your vehicle", "Your documents", "Where you deliver", "Getting paid", "Safety & first delivery"];
const DOCUMENTS = [
  { type: "identity", label: "Identification", helper: "Upload a clear Zimbabwe ID or other approved identity document." },
  { type: "licence", label: "Driver licence", helper: "Upload the licence you will use while delivering." },
  { type: "registration", label: "Vehicle registration", helper: "Upload the registration document for your vehicle." },
  { type: "insurance", label: "Vehicle insurance", helper: "Upload current vehicle insurance where required." }
];

const ACTIVE_ACTIONS = {
  driver_assigned: { title: "Go to the business", button: "Start going to pickup", action: "start_to_pickup", destination: "pickup" },
  driver_to_pickup: { title: "Go to the business", button: "I arrived", action: "arrive_pickup", destination: "pickup" },
  driver_arrived_pickup: { title: "Collect the order", button: "Check pickup code", action: "begin_pickup_verification", destination: "pickup" },
  pickup_verification: { title: "Confirm pickup", button: "Order collected", action: "verify_pickup", code: "pickup" },
  collected: { title: "Ready to deliver", button: "Start delivery", action: "start_delivery", destination: "dropoff" },
  en_route: { title: "Go to the customer", button: "I arrived", action: "arrive_customer", destination: "dropoff" },
  driver_arrived_customer: { title: "Customer handoff", button: "Ask for delivery PIN", action: "begin_handoff", destination: "dropoff" },
  handoff_verification: { title: "Confirm delivery", button: "Complete delivery", action: "complete", code: "handoff" }
};

function labelStatus(value = "") { return String(value).replaceAll("_", " "); }
function dateTime(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("en-ZW", { dateStyle: "medium", timeStyle: "short" }); }

function useDriverData() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async ({ quiet = false } = {}) => {
    if (!quiet) setLoading(true); setError("");
    try { setData(await authenticatedFetch("/api/driver/bootstrap")); }
    catch (err) { setError(err.message || "Driver information could not be loaded."); }
    finally { if (!quiet) setLoading(false); }
  }, []);
  useEffect(() => { load(); const timer = window.setInterval(() => load({ quiet: true }), 10000); return () => clearInterval(timer); }, [load]);
  return { data, loading, error, load };
}

function ProgressSteps({ current }) {
  return <div className="grid grid-cols-6 gap-2">{APPLICATION_STEPS.map((label, index) => <div key={label} className="min-w-0"><div className={cn("h-1.5 rounded-full", index <= current ? "bg-[var(--accent)]" : "bg-[var(--border)]")} /><p className={cn("mt-2 hidden truncate text-[11px] sm:block", index === current ? "font-semibold text-[var(--accent)]" : "text-tertiary")}>{label}</p></div>)}</div>;
}

function DriverApplication({ data, reload }) {
  const { user, profile } = useAuth(); const { toast } = useToast();
  const existing = data?.application || {};
  const [step, setStep] = useState(Math.min(Number(existing.currentStep || 0), 5));
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(""); const [error, setError] = useState("");
  const vehicle = data?.vehicles?.[0] || {};
  const [form, setForm] = useState({
    legalName: existing.legalName || profile?.displayName || user?.displayName || "", phone: existing.phone || profile?.phoneNumber || user?.phoneNumber || "", city: existing.city || "Harare",
    emergencyContactName: existing.emergencyContactName || "", emergencyContactPhone: existing.emergencyContactPhone || "", preferredZones: (existing.preferredZones || []).join(", "),
    vehicleType: vehicle.type || "motorcycle", registration: vehicle.registration || "", make: vehicle.make || "", model: vehicle.model || "", ownership: vehicle.ownership || "driver_owned",
    payoutType: "mobile_money", payoutProvider: "EcoCash", payoutName: existing.legalName || profile?.displayName || "", payoutIdentifier: "", agreementsAccepted: Boolean(existing.agreementsAccepted), locationConsent: Boolean(existing.locationConsent)
  });
  useEffect(() => { setStep(Math.min(Number(data?.application?.currentStep ?? step), 5)); }, [data?.application?.currentStep]);
  const uploaded = new Map((data?.documents || []).map((item) => [item.type, item]));
  const reviewState = ["application_submitted", "under_review", "information_required", "approved"].includes(existing.status) && !editing;

  async function saveStep(nextStep = step) {
    setSaving(true); setError("");
    try {
      await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "save", application: {
        legalName: form.legalName, phone: form.phone, city: form.city, emergencyContactName: form.emergencyContactName, emergencyContactPhone: form.emergencyContactPhone,
        preferredZones: form.preferredZones.split(",").map((item) => item.trim()).filter(Boolean), currentStep: nextStep, agreementsAccepted: form.agreementsAccepted, locationConsent: form.locationConsent
      }, vehicle: { type: form.vehicleType, registration: form.registration || "PENDING", make: form.make, model: form.model, ownership: form.ownership } }) });
      await reload({ quiet: true });
      return true;
    } catch (err) { setError(err.message); return false; }
    finally { setSaving(false); }
  }
  async function nextStep() {
    if (step === 0 && (!form.legalName.trim() || !form.phone.trim() || !form.city.trim())) { setError("Add your name, phone and city before continuing."); return; }
    if (step === 1 && (!form.registration.trim() || !form.vehicleType)) { setError("Add your vehicle registration before continuing."); return; }
    if (step === 2 && !uploaded.has("identity")) { setError("Upload your identification before continuing."); return; }
    if (step === 2 && !uploaded.has("licence")) { setError("Upload your Driver licence before continuing."); return; }
    if (step === 4 && !existing.payoutComplete && !form.payoutIdentifier.trim()) { setError("Add where Spotly should send your earnings."); return; }
    if (step === 5 && (!form.agreementsAccepted || !form.locationConsent)) { setError("Accept the Driver and location terms before submitting."); return; }
    if (!(await saveStep(Math.min(step + 1, 5)))) return;
    if (step === 4 && !existing.payoutComplete) {
      await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "payout", payout: { type: form.payoutType, provider: form.payoutProvider, recipientName: form.payoutName || form.legalName, identifier: form.payoutIdentifier } }) });
    }
    if (step < 5) setStep((value) => value + 1);
  }
  async function uploadDocument(type, file) {
    if (!file) return; setUploading(type); setError("");
    try {
      const safe = file.name.replace(/[^A-Za-z0-9._-]/g, "_"); const path = `driver-applications/${user.uid}/documents/${type}/${Date.now()}-${safe}`;
      await uploadFile(path, file, { driverId: user.uid, documentType: type, ownerId: user.uid });
      await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "document", document: { type, storagePath: path, fileName: file.name } }) });
      toast(`${DOCUMENTS.find((item) => item.type === type)?.label || "Document"} uploaded.`, { type: "success" }); await reload({ quiet: true });
    } catch (err) { setError(err.message || "The document could not be uploaded."); }
    finally { setUploading(""); }
  }
  async function finishTraining() { setSaving(true); try { await saveStep(5); await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "training", trainingComplete: true }) }); await reload({ quiet: true }); toast("Safety training marked complete.", { type: "success" }); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function submit() { setSaving(true); setError(""); try { await saveStep(5); if (!data?.application?.trainingComplete) await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "training", trainingComplete: true }) }); await authenticatedFetch("/api/driver/application", { method: "POST", body: JSON.stringify({ action: "submit" }) }); await reload(); toast("Your Driver application was sent to Spotly.", { type: "success" }); } catch (err) { setError(err.message); } finally { setSaving(false); } }

  if (reviewState) return <div className="space-y-6"><PageHeader eyebrow="Spotly Driver" title={existing.status === "information_required" ? "We need one more thing from you" : existing.status === "approved" ? "You're approved" : "Spotly is reviewing your application"} description={existing.status === "information_required" ? existing.reviewReason || "Review the item below and update it." : existing.status === "approved" ? "Your Driver account is being prepared for deliveries." : "You can see each part independently while Spotly reviews it."} />{existing.status === "information_required" && <Card className="border-warning p-5"><p className="font-semibold">Your action</p><p className="mt-2 text-sm text-secondary">{existing.reviewReason || "Update the requested information, then submit again."}</p><Button className="mt-4" onClick={() => { setStep(2); setEditing(true); }}>Review application</Button></Card>}<SectionCard title="Application review"><div className="divide-y">{(data?.readiness?.checks || []).map((item) => <div key={item.id} className="flex items-center gap-3 py-4"><span className={cn("flex h-9 w-9 items-center justify-center rounded-lg", item.ok ? "bg-[var(--success-soft)] text-success" : "bg-[var(--warning-soft)] text-warning")}>{item.ok ? <CheckCircle2 className="h-5 w-5" /> : <Clock3 className="h-5 w-5" />}</span><span className="flex-1 font-medium">{item.label}</span><Badge tone={item.ok ? "success" : "warning"}>{item.ok ? "Complete" : "Needs attention"}</Badge></div>)}</div></SectionCard>{existing.status === "information_required" && <Button variant="outline" onClick={() => { setStep(0); setEditing(true); }}>Edit application</Button>}</div>;

  return <div className="space-y-6"><PageHeader eyebrow={`Step ${step + 1} of ${APPLICATION_STEPS.length}`} title="Get ready to deliver" description="Complete one clear step at a time. Spotly saves your progress." /><ProgressSteps current={step} />{error && <div role="alert" className="rounded-xl border border-[color-mix(in_srgb,var(--danger)_35%,var(--border))] bg-[var(--danger-soft)] p-4 text-sm text-[var(--on-danger-soft)]">{error}</div>}
  {step === 0 && <SectionCard title="Your details" description="Tell Spotly who you are and how to reach you."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Full legal name<input className="field-control mt-2 w-full" value={form.legalName} onChange={(e) => setForm({ ...form, legalName: e.target.value })} /></label><label className="text-sm font-medium">Phone<input className="field-control mt-2 w-full" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+263" /></label><label className="text-sm font-medium">City<input className="field-control mt-2 w-full" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label className="text-sm font-medium">Emergency contact<input className="field-control mt-2 w-full" value={form.emergencyContactName} onChange={(e) => setForm({ ...form, emergencyContactName: e.target.value })} /></label><label className="text-sm font-medium">Emergency phone<input className="field-control mt-2 w-full" value={form.emergencyContactPhone} onChange={(e) => setForm({ ...form, emergencyContactPhone: e.target.value })} /></label></div></SectionCard>}
  {step === 1 && <SectionCard title="Your vehicle" description="Spotly uses this to match you with deliveries your vehicle can safely carry."><div className="grid gap-3 sm:grid-cols-4">{["motorcycle", "car", "van", "bicycle"].map((type) => <button type="button" key={type} onClick={() => setForm({ ...form, vehicleType: type })} className={cn("rounded-xl border p-4 text-left capitalize", form.vehicleType === type && "border-[var(--accent)] bg-[var(--accent-soft)] ring-2 ring-[color-mix(in_srgb,var(--accent)_15%,transparent)]")}><Bike className="h-5 w-5" /><p className="mt-3 font-semibold">{type}</p></button>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Registration<input className="field-control mt-2 w-full uppercase" value={form.registration} onChange={(e) => setForm({ ...form, registration: e.target.value })} /></label><label className="text-sm font-medium">Make<input className="field-control mt-2 w-full" value={form.make} onChange={(e) => setForm({ ...form, make: e.target.value })} /></label><label className="text-sm font-medium">Model<input className="field-control mt-2 w-full" value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /></label></div></SectionCard>}
  {step === 2 && <SectionCard title="Your documents" description="Upload clear photos or files. You can replace a document if Spotly asks for a clearer copy."><div className="grid gap-4 md:grid-cols-2">{DOCUMENTS.map((item) => { const doc = uploaded.get(item.type); return <Card key={item.type} className="p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><IdCard className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.label}</p>{doc && <Badge tone={doc.status === "approved" ? "success" : doc.status === "rejected" ? "danger" : "warning"}>{labelStatus(doc.status)}</Badge>}</div><p className="mt-1 text-sm leading-5 text-secondary">{doc?.reviewReason || item.helper}</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-[var(--surface-2)]"><Upload className="h-4 w-4" />{uploading === item.type ? "Uploading…" : doc ? "Replace document" : "Upload document"}<input type="file" accept="image/*,.pdf" className="sr-only" disabled={Boolean(uploading)} onChange={(event) => uploadDocument(item.type, event.target.files?.[0])} /></label></div></div></Card>; })}</div></SectionCard>}
  {step === 3 && <SectionCard title="Where you want to deliver" description="These are preferences, not guaranteed jobs."><label className="text-sm font-medium">Preferred areas <span className="font-normal text-tertiary">separate with commas</span><input className="field-control mt-2 w-full" value={form.preferredZones} onChange={(e) => setForm({ ...form, preferredZones: e.target.value })} placeholder="Borrowdale, Highlands, Avondale" /></label><div className="mt-4 rounded-xl bg-[var(--surface-2)] p-4 text-sm text-secondary"><MapPin className="mb-2 h-5 w-5 text-[var(--accent)]" />You can still receive eligible nearby deliveries when Spotly's dispatch zone includes your current location.</div></SectionCard>}
  {step === 4 && <SectionCard title="Getting paid" description="Add the destination Spotly should use for Driver payouts."><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Payout type<select className="field-control mt-2 w-full" value={form.payoutType} onChange={(e) => setForm({ ...form, payoutType: e.target.value })}><option value="mobile_money">Mobile money</option><option value="bank">Bank account</option></select></label><label className="text-sm font-medium">Provider<input className="field-control mt-2 w-full" value={form.payoutProvider} onChange={(e) => setForm({ ...form, payoutProvider: e.target.value })} /></label><label className="text-sm font-medium">Recipient name<input className="field-control mt-2 w-full" value={form.payoutName} onChange={(e) => setForm({ ...form, payoutName: e.target.value })} /></label><label className="text-sm font-medium">Account / wallet identifier<input className="field-control mt-2 w-full" value={form.payoutIdentifier} onChange={(e) => setForm({ ...form, payoutIdentifier: e.target.value })} placeholder={existing.payoutComplete ? "Already saved" : "Enter securely"} /></label></div>{existing.payoutComplete && <p className="mt-4 text-sm font-semibold text-success">Payout details saved.</p>}</SectionCard>}
  {step === 5 && <div className="space-y-4"><SectionCard title="Safety & first delivery" description="Know the important rules before your first live delivery."><div className="grid gap-3 sm:grid-cols-2">{["Use navigation only when safely stopped.", "Verify the pickup code before leaving.", "Keep customer addresses private.", "Never ask a customer to reveal their PIN before handoff.", "Report damaged orders before continuing.", "Use Need help? for breakdowns and safety problems."].map((text) => <div key={text} className="flex gap-3 rounded-xl bg-[var(--surface-2)] p-4 text-sm"><ShieldCheck className="h-5 w-5 shrink-0 text-[var(--accent)]" /><span>{text}</span></div>)}</div><div className="mt-5 space-y-3"><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={form.locationConsent} onChange={(e) => setForm({ ...form, locationConsent: e.target.checked })} /><span>I understand Spotly uses my location while I am online to send nearby deliveries and show delivery progress.</span></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={form.agreementsAccepted} onChange={(e) => setForm({ ...form, agreementsAccepted: e.target.checked })} /><span>I accept the Driver operating terms and safety rules presented by Spotly.</span></label></div><Button className="mt-5" variant="outline" onClick={finishTraining} loading={saving}>{existing.trainingComplete ? <><CheckCircle2 className="h-4 w-4" />Training complete</> : "Mark training complete"}</Button></SectionCard><Button className="w-full" size="lg" onClick={submit} loading={saving}>Submit to Spotly</Button></div>}
  <div className="flex justify-between gap-3">{step > 0 ? <Button variant="outline" onClick={() => setStep((value) => value - 1)}>Back</Button> : <span />}{step < 5 && <Button onClick={nextStep} loading={saving}>{step === 0 ? "Add vehicle details" : step === 1 ? "Add required documents" : step === 2 ? "Choose delivery areas" : step === 3 ? "Set up getting paid" : "Review safety training"}</Button>}</div></div>;
}

function OfferCard({ offer, onAccept, onDecline, busy }) {
  return <Card className="overflow-hidden"><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.08em] text-tertiary">{offer.number || "DELIVERY"}</p><h3 className="mt-2 text-lg font-semibold">{offer.pickup?.name || "Pickup"}</h3><p className="mt-1 text-sm text-secondary">{offer.pickup?.area} → {offer.dropoff?.area}</p></div><div className="text-right"><p className="text-2xl font-semibold">{formatCurrency(offer.pay || 0, offer.currency)}</p><p className="mt-1 text-xs text-secondary">Guaranteed pay</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-[var(--surface-2)] p-3"><p className="text-xs font-semibold text-tertiary">DISTANCE TO PICKUP</p><p className="mt-2 font-semibold">{Number(offer.distanceKm || 0).toFixed(1)} km</p></div><div className="rounded-lg bg-[var(--surface-2)] p-3"><p className="text-xs font-semibold text-tertiary">EXPECTED TIME</p><p className="mt-2 font-semibold">~{offer.expectedMinutes || "—"} min</p></div><div className="rounded-lg bg-[var(--surface-2)] p-3"><p className="text-xs font-semibold text-tertiary">LOAD</p><p className="mt-2 font-semibold">{offer.bagCount || 1} bag{offer.bagCount === 1 ? "" : "s"}</p></div></div></div><div className="flex gap-2 border-t p-3"><Button variant="outline" className="flex-1" disabled={busy} onClick={() => onDecline(offer)}>Decline</Button><Button className="flex-[1.5]" loading={busy} onClick={() => onAccept(offer)}>Accept delivery</Button></div></Card>;
}

function Availability({ data, reload }) {
  const { enablePushNotifications } = useAuth(); const { toast } = useToast(); const [busy, setBusy] = useState(false); const [permissionError, setPermissionError] = useState("");
  const online = data?.presence?.online === true;
  async function setOnline(next) {
    setBusy(true); setPermissionError("");
    try {
      if (!next) { await authenticatedFetch("/api/driver/presence", { method: "POST", body: JSON.stringify({ online: false }) }); await reload(); return; }
      if (!navigator.geolocation) throw new Error("This device does not support location. Use a phone or browser with location access.");
      const position = await new Promise((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, () => reject(new Error("Turn on location to receive nearby deliveries.")), { enableHighAccuracy: true, timeout: 12000, maximumAge: 15000 }));
      await authenticatedFetch("/api/driver/presence", { method: "POST", body: JSON.stringify({ online: true, location: { lat: position.coords.latitude, lng: position.coords.longitude, accuracy: position.coords.accuracy } }) });
      enablePushNotifications().catch(() => {}); await reload(); toast("You're online. Spotly can now send nearby deliveries.", { type: "success" });
    } catch (err) { setPermissionError(err.message); }
    finally { setBusy(false); }
  }
  return <Card className={cn("p-5", online && "border-[color-mix(in_srgb,var(--success)_35%,var(--border))]")}><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className={cn("flex h-14 w-14 items-center justify-center rounded-xl", online ? "bg-[var(--success)] text-[var(--on-success)]" : "bg-[var(--surface-2)] text-secondary")}><Bike className="h-6 w-6" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{online ? data?.presence?.currentJobId ? "You're on a delivery" : "You're online" : "You're offline"}</h2><StatusBadge status={online ? "Online" : "Offline"} /></div><p className="mt-1 text-sm text-secondary">{online ? "Location sharing is on while you are online." : "Go online when you are ready to receive nearby deliveries."}</p>{permissionError && <p className="mt-2 text-sm font-medium text-danger">{permissionError}</p>}</div><Button variant={online ? "outline" : "primary"} loading={busy} disabled={Boolean(online && data?.activeJob)} title={online && data?.activeJob ? "Finish your active delivery before going offline." : undefined} onClick={() => setOnline(!online)}>{online ? data?.activeJob ? <><Navigation className="h-4 w-4" />On delivery</> : <><X className="h-4 w-4" />Go offline</> : <><Play className="h-4 w-4" />Go online</>}</Button></div></Card>;
}

function LiveLocation({ data }) {
  const online = data?.presence?.online === true; const sentAt = useRef(0); const watcher = useRef(null);
  useEffect(() => {
    if (!online || !navigator.geolocation) return undefined;
    watcher.current = navigator.geolocation.watchPosition((position) => {
      if (Date.now() - sentAt.current < 15000) return; sentAt.current = Date.now();
      authenticatedFetch("/api/driver/location", { method: "POST", body: JSON.stringify({ lat: position.coords.latitude, lng: position.coords.longitude, accuracy: position.coords.accuracy }) }).catch(() => {});
    }, () => {}, { enableHighAccuracy: true, maximumAge: 10000, timeout: 15000 });
    return () => { if (watcher.current != null) navigator.geolocation.clearWatch(watcher.current); };
  }, [online]);
  return null;
}

function DriverHome({ data, reload, onOffer }) {
  const { profile, user } = useAuth(); const router = useRouter(); const name = (profile?.displayName || data?.driver?.displayName || user?.displayName || "Driver").split(" ")[0];
  return <div className="space-y-6"><PageHeader eyebrow={new Date().toLocaleDateString("en-ZW", { weekday: "long", day: "numeric", month: "long" })} title={`Hello, ${name}`} description={data.activeJob ? "You have an active delivery. Continue from the exact step where you stopped." : "Go online when you are ready to deliver."} actions={data.activeJob ? <Button onClick={() => router.push("/driver/active")}>Open active delivery</Button> : undefined} /><Availability data={data} reload={reload} />{data.activeJob ? <Card className="p-5"><p className="text-sm font-semibold text-[var(--accent)]">Current delivery</p><div className="mt-2 flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Navigation className="h-6 w-6" /></span><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold">{ACTIVE_ACTIONS[data.activeJob.state]?.title || labelStatus(data.activeJob.state)}</h2><p className="mt-1 text-sm text-secondary">{data.activeJob.number}</p></div><Button onClick={() => router.push("/driver/active")}>Open</Button></div></Card> : data.presence?.online && data.offers?.length ? <div><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-semibold text-[var(--accent)]">Delivery available</p><h2 className="mt-1 text-2xl font-semibold">See the pay before you accept</h2></div><Link href="/driver/jobs" className="text-sm font-semibold text-[var(--accent)]">All offers</Link></div><OfferCard offer={data.offers[0]} onAccept={onOffer.accept} onDecline={onOffer.decline} busy={onOffer.busy} /></div> : <EmptyState icon={data.presence?.online ? PackageCheck : Bike} title={data.presence?.online ? "No deliveries nearby right now" : "You're not receiving deliveries"} description={data.presence?.online ? "Spotly will show a delivery here when one becomes available nearby." : "Go online only when you are ready to travel safely."} />}</div>;
}

function Jobs({ data, offer }) {
  if (!data.presence?.online) return <div className="space-y-6"><PageHeader {...sectionMeta.jobs} /><EmptyState icon={Bike} title="Go online to receive deliveries" description="Return to Driver home and turn on location sharing when you are ready." action={<Button asChild><Link href="/driver">Go to Driver home</Link></Button>} /></div>;
  if (data.activeJob) return <div className="space-y-6"><PageHeader {...sectionMeta.jobs} /><EmptyState icon={Navigation} title="Finish your active delivery first" description="Spotly keeps one active delivery at a time for a clear, safe workflow." action={<Button asChild><Link href="/driver/active">Open active delivery</Link></Button>} /></div>;
  return <div className="space-y-6"><PageHeader {...sectionMeta.jobs} />{data.offers?.length ? <div className="grid gap-4 xl:grid-cols-2">{data.offers.map((item) => <OfferCard key={item.id} offer={item} onAccept={offer.accept} onDecline={offer.decline} busy={offer.busy} />)}</div> : <EmptyState icon={PackageCheck} title="No deliveries nearby right now" description="Stay online. New delivery offers appear here and can also arrive by push notification." />}</div>;
}

function ActiveJob({ data, reload }) {
  const { toast } = useToast(); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const job = data.activeJob;
  if (!job) return <div className="space-y-6"><PageHeader {...sectionMeta.active} /><EmptyState icon={Navigation} title="No active delivery" description="Accept a delivery while online and it will appear here." action={<Button asChild><Link href="/driver/jobs">View deliveries</Link></Button>} /></div>;
  const step = ACTIVE_ACTIONS[job.state]; const destination = step?.destination === "dropoff" ? job.dropoff : job.pickup;
  function navigate() { if (!destination) return; const coords = Number.isFinite(Number(destination.lat)) && Number.isFinite(Number(destination.lng)) ? `${destination.lat},${destination.lng}` : encodeURIComponent(destination.formattedAddress || ""); window.open(`https://www.google.com/maps/dir/?api=1&destination=${coords}`, "_blank", "noopener,noreferrer"); }
  async function act() { if (!step) return; setBusy(true); setError(""); try { await authenticatedFetch("/api/driver/delivery", { method: "POST", body: JSON.stringify({ deliveryJobId: job.id, action: step.action, code: step.code ? code.trim() : undefined }) }); setCode(""); await reload(); toast(step.action === "complete" ? `Delivery complete. You earned ${formatCurrency(job.acceptedDriverPay || job.quotedDriverPay || 0, job.currency)}.` : "Delivery updated.", { type: "success" }); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="space-y-6"><PageHeader eyebrow={job.number} title={step?.title || labelStatus(job.state)} description="One delivery. One next action." />{error && <div role="alert" className="rounded-xl border border-[color-mix(in_srgb,var(--danger)_35%,var(--border))] bg-[var(--danger-soft)] p-4 text-sm text-[var(--on-danger-soft)]">{error}</div>}<Card className="overflow-hidden"><div className="p-6 sm:p-8"><p className="text-xs font-semibold tracking-[.08em] text-tertiary">NEXT DESTINATION</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em]">{step?.destination === "dropoff" ? job.dropoff?.formattedAddress || job.dropoff?.suburb || "Customer" : job.pickup?.formattedAddress || job.pickup?.area || "Business"}</h2><p className="mt-3 text-sm leading-6 text-secondary">{step?.destination === "dropoff" ? [job.dropoff?.landmark, job.dropoff?.instructions].filter(Boolean).join(" · ") || "Customer delivery address" : job.pickup?.instructions || "Go to the business collection point."}</p>{destination && <Button className="mt-5" variant="outline" onClick={navigate}><Navigation className="h-4 w-4" />Open navigation</Button>}</div><div className="border-t bg-[var(--surface-2)] p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-semibold text-tertiary">PAY</p><p className="mt-1 text-lg font-semibold">{formatCurrency(job.acceptedDriverPay || job.quotedDriverPay || 0, job.currency)}</p></div><div><p className="text-xs font-semibold text-tertiary">BAGS</p><p className="mt-1 text-lg font-semibold">{job.bagCount || 1}</p></div><div><p className="text-xs font-semibold text-tertiary">STATE</p><p className="mt-1 text-lg font-semibold capitalize">{labelStatus(job.state)}</p></div></div></div></Card>{step?.code && <Card className="p-5"><label className="text-sm font-medium">{step.code === "pickup" ? "Pickup code from the business" : "4-digit PIN from the customer"}<input inputMode="numeric" autoComplete="one-time-code" className="field-control mt-2 h-14 w-full text-center text-2xl font-semibold tracking-[.3em]" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 8))} placeholder="••••" /></label><p className="mt-2 text-xs text-secondary">{step.code === "pickup" ? "Do not leave until the pickup code is confirmed." : "The customer must tell you the PIN at handoff. Spotly never needs you to guess it."}</p></Card>}{step ? <Button size="lg" className="w-full min-h-14 text-base" loading={busy} disabled={Boolean(step.code && code.length < 4)} onClick={act}>{step.button}</Button> : <EmptyState icon={CheckCircle2} title="Delivery state updated" description="Refresh if another action is expected." action={<Button onClick={reload}><RefreshCw className="h-4 w-4" />Refresh</Button>} />}<Button asChild variant="outline" className="w-full"><Link href={`/driver/support?delivery=${job.id}`}><AlertTriangle className="h-4 w-4" />Need help with this delivery?</Link></Button></div>;
}

function Earnings({ data, reload }) {
  const ledger = data.earnings || []; const payouts = data.payouts || []; const { toast } = useToast();
  const fallbackAvailable = ledger.filter((item) => (item.bucket || "available") === "available").reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const balance = data.balances?.USD || {}; const available = data.balances?.USD ? Number(balance.available || 0) : fallbackAvailable; const paid = data.balances?.USD ? Number(balance.paid_out || 0) : ledger.filter((item) => item.bucket === "paid_out").reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const reserved = Number(balance.reserved || 0); const processing = Number(balance.processing || 0); const minimum = Number(data.payoutPolicy?.minimum || 20); const [amount,setAmount]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function requestPayout(){const numeric=Number(amount);if(!Number.isFinite(numeric)||numeric<=0)return;setBusy(true);setError("");try{await authenticatedFetch("/api/driver/payout",{method:"POST",body:JSON.stringify({action:"request",amount:numeric,currency:"USD"})});setAmount("");await reload();toast("Your payout request was sent to Spotly.",{type:"success"});}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <div className="space-y-6"><PageHeader {...sectionMeta.earnings} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><CircleDollarSign className="h-5 w-5 text-[var(--accent)]" /><p className="mt-4 text-sm text-secondary">Available</p><p className="mt-1 text-3xl font-semibold">{formatCurrency(available)}</p></Card><Card className="p-5"><Clock3 className="h-5 w-5 text-[var(--accent)]" /><p className="mt-4 text-sm text-secondary">Payout in progress</p><p className="mt-1 text-3xl font-semibold">{formatCurrency(reserved+processing)}</p></Card><Card className="p-5"><WalletCards className="h-5 w-5 text-[var(--accent)]" /><p className="mt-4 text-sm text-secondary">Paid out</p><p className="mt-1 text-3xl font-semibold">{formatCurrency(paid)}</p></Card><Card className="p-5"><PackageCheck className="h-5 w-5 text-[var(--accent)]" /><p className="mt-4 text-sm text-secondary">Completed earning events</p><p className="mt-1 text-3xl font-semibold">{ledger.filter((item)=>item.type==="delivery_earned").length}</p></Card></div>
  <div className="grid gap-5 lg:grid-cols-2"><SectionCard title="Request a payout" description={`Minimum ${formatCurrency(minimum)} · ${String(data.payoutPolicy?.cadence||"weekly").replaceAll("_"," ")}`}><div className="space-y-4"><div className="rounded-xl bg-[var(--surface-2)] p-4"><p className="text-xs font-semibold text-tertiary">PAYOUT ACCOUNT</p><p className="mt-2 font-semibold">{data.payoutAccount ? `${data.payoutAccount.provider || data.payoutAccount.type} · ${data.payoutAccount.maskedIdentifier || "Saved"}` : "Not set up"}</p><p className="mt-1 text-sm capitalize text-secondary">{labelStatus(data.payoutAccount?.verificationState || "not verified")}</p></div>{error&&<p role="alert" className="rounded-lg bg-[var(--danger-soft)] p-3 text-sm text-[var(--on-danger-soft)]">{error}</p>}<label className="text-sm font-medium">Payout amount (USD)<input className="field-control mt-2 w-full" type="number" min={minimum} max={available} step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)} placeholder={Math.max(minimum,available).toFixed(2)}/></label><Button onClick={requestPayout} loading={busy} disabled={data.payoutAccount?.verificationState!=="verified"||Number(amount)<minimum||Number(amount)>available}>Request payout</Button>{data.payoutAccount?.verificationState!=="verified"&&<p className="text-xs leading-5 text-secondary">Spotly must verify your payout account before money can be sent. Your earnings remain available until you request a payout.</p>}</div></SectionCard><SectionCard title="Payout history">{payouts.length?<div className="divide-y">{payouts.map((item)=><div key={item.id} className="flex items-center gap-4 py-3"><div className="min-w-0 flex-1"><p className="font-medium">{formatCurrency(item.amount||0,item.currency)}</p><p className="mt-1 text-xs text-secondary">{dateTime(item.createdAt)}{item.reference?` · ${item.reference}`:""}</p></div><StatusBadge status={item.status||"requested"}/></div>)}</div>:<EmptyState icon={WalletCards} title="No payouts yet" description="Requested and completed payouts will appear here."/>}</SectionCard></div>
  <SectionCard title="Earnings statement">{ledger.length ? <div className="divide-y">{ledger.map((item) => <div key={item.id} className="flex items-center gap-4 py-4"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--success-soft)] text-success"><CircleDollarSign className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-medium capitalize">{labelStatus(item.type)}</p><p className="mt-1 text-xs text-secondary">{dateTime(item.createdAt)} · {item.deliveryJobId || item.description || "Driver earnings"}</p></div><p className="font-semibold">{formatCurrency(item.amount || 0, item.currency)}</p></div>)}</div> : <EmptyState icon={CircleDollarSign} title="No earnings yet" description="Completed live deliveries will appear here automatically." />}</SectionCard></div>;
}

function HistoryView({ data }) {
  const jobs = (data.jobs || []).filter((item) => ["delivered", "failed", "cancelled", "returned"].includes(item.state));
  return <div className="space-y-6"><PageHeader {...sectionMeta.history} />{jobs.length ? <div className="space-y-3">{jobs.map((job) => <Card key={job.id} className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-tertiary">{job.number}</p><h3 className="mt-2 font-semibold">{job.pickup?.area || "Pickup"} → {job.dropoff?.suburb || job.dropoff?.area || "Customer"}</h3><p className="mt-1 text-sm text-secondary">{dateTime(job.deliveredAt || job.updatedAt)}</p></div><div className="text-right"><StatusBadge status={job.state} /><p className="mt-3 font-semibold">{formatCurrency(job.acceptedDriverPay || job.quotedDriverPay || 0, job.currency)}</p></div></div></Card>)}</div> : <EmptyState icon={History} title="No completed deliveries yet" description="Your completed work will appear here." />}</div>;
}

function Support({ data }) {
  const [category, setCategory] = useState("breakdown"); const [description, setDescription] = useState(""); const [severity, setSeverity] = useState("medium"); const [busy, setBusy] = useState(false); const { toast } = useToast();
  async function report() { if (description.trim().length < 3) return; setBusy(true); try { await authenticatedFetch("/api/driver/incidents", { method: "POST", body: JSON.stringify({ deliveryJobId: data.activeJob?.id, category, description, severity }) }); setDescription(""); toast("The incident was sent to Spotly Operations.", { type: "success" }); } catch (err) { toast(err.message, { type: "error" }); } finally { setBusy(false); } }
  return <div className="space-y-6"><PageHeader {...sectionMeta.support} /><div className="grid gap-5 lg:grid-cols-2"><SectionCard title="Report a delivery problem" description={data.activeJob ? `Spotly will attach ${data.activeJob.number} automatically.` : "You can report a Driver safety or operational issue."}><div className="space-y-4"><label className="text-sm font-medium">What happened?<select className="field-control mt-2 w-full" value={category} onChange={(e) => setCategory(e.target.value)}><option value="safety">Safety emergency / concern</option><option value="breakdown">Vehicle breakdown</option><option value="customer_unreachable">Cannot reach customer</option><option value="address_problem">Cannot find address</option><option value="business_problem">Business problem</option><option value="customer_problem">Customer problem</option><option value="order_damaged">Order damaged</option><option value="other">Other</option></select></label><label className="text-sm font-medium">Urgency<select className="field-control mt-2 w-full" value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="text-sm font-medium">Tell Spotly what happened<textarea className="field-control mt-2 min-h-28 w-full" value={description} onChange={(e) => setDescription(e.target.value)} /></label><Button onClick={report} loading={busy} disabled={description.trim().length < 3}>Send incident to Spotly</Button></div></SectionCard><SectionCard title="Other support"><div className="space-y-3"><Button asChild variant="outline" className="w-full justify-start"><Link href="/support?topic=driver-account"><UserRound className="h-4 w-4" />Driver account help</Link></Button><Button asChild variant="outline" className="w-full justify-start"><Link href="/support?topic=driver-payment"><WalletCards className="h-4 w-4" />Earnings and payout help</Link></Button><Button asChild variant="outline" className="w-full justify-start"><Link href="/support?topic=safety-guidance"><ShieldCheck className="h-4 w-4" />Safety guidance</Link></Button></div></SectionCard></div></div>;
}

function Profile({ data }) {
  const driver = data.driver || {}; const vehicle = data.vehicles?.[0];
  return <div className="space-y-6"><PageHeader {...sectionMeta.profile} actions={<Button asChild variant="outline"><Link href="/account">Account settings</Link></Button>} /><Card className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="flex h-14 w-14 items-center justify-center rounded-xl bg-[var(--accent)] text-[var(--on-accent)]"><UserRound className="h-6 w-6" /></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold">{driver.displayName || driver.legalName || data.application?.legalName || "Spotly Driver"}</h2><Badge tone={["ready", "active", "approved"].includes(driver.status) ? "success" : "warning"}>{labelStatus(driver.status || data.application?.status || "application")}</Badge></div><p className="mt-1 text-sm text-secondary">{driver.city || data.application?.city || "Zimbabwe"}</p></div></div></Card><div className="grid gap-5 lg:grid-cols-2"><SectionCard title="Vehicle"><div className="rounded-xl bg-[var(--surface-2)] p-4"><p className="font-semibold capitalize">{vehicle?.type || "Vehicle not added"}</p><p className="mt-1 text-sm text-secondary">{[vehicle?.registration, vehicle?.make, vehicle?.model].filter(Boolean).join(" · ") || "Complete your vehicle setup"}</p><p className="mt-3 text-xs font-semibold capitalize text-[var(--accent)]">{labelStatus(vehicle?.status || "pending")}</p></div></SectionCard><SectionCard title="Documents"><div className="divide-y">{(data.documents || []).map((item) => <div key={item.id} className="flex items-center gap-3 py-3"><FileCheck2 className="h-5 w-5 text-[var(--accent)]" /><span className="flex-1 capitalize">{labelStatus(item.type)}</span><Badge tone={item.status === "approved" ? "success" : item.status === "rejected" ? "danger" : "warning"}>{labelStatus(item.status)}</Badge></div>)}</div></SectionCard></div><SectionCard title="Why can I go online?"><div className="divide-y">{(data.eligibility?.checks || []).map((check) => <div key={check.id} className="flex items-center gap-3 py-3"><span className={cn("flex h-8 w-8 items-center justify-center rounded-lg", check.ok ? "bg-[var(--success-soft)] text-success" : "bg-[var(--danger-soft)] text-danger")}>{check.ok ? <CheckCircle2 className="h-4 w-4" /> : <X className="h-4 w-4" />}</span><span className="flex-1 text-sm font-medium">{check.label}</span></div>)}</div></SectionCard></div>;
}

export function DriverApp({ section = "home" }) {
  const safe = sectionMeta[section] ? section : "home"; const { data, loading, error, load } = useDriverData(); const { toast } = useToast(); const router = useRouter(); const [offerBusy, setOfferBusy] = useState(false);
  async function offerAction(offer, action) { setOfferBusy(true); try { const result = await authenticatedFetch("/api/driver/offers", { method: "POST", body: JSON.stringify({ offerId: offer.id, action }) }); await load(); if (action === "accept") { toast("Delivery accepted.", { type: "success" }); router.push("/driver/active"); } } catch (err) { toast(err.message, { type: "error" }); await load({ quiet: true }); } finally { setOfferBusy(false); } }
  const offer = { accept: (item) => offerAction(item, "accept"), decline: (item) => offerAction(item, "decline"), busy: offerBusy };
  return <AuthGate portal="driver" title="Sign in to Spotly Driver"><PortalShell portalId="driver" activeSection={safe}><div className="mx-auto max-w-[1280px] px-4 py-7 sm:px-6 lg:px-8 lg:py-9">{loading ? <div className="flex min-h-[50vh] items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-driver" /></div> : error ? <EmptyState icon={AlertTriangle} title="Driver could not be loaded" description={error} action={<Button onClick={() => load()}><RefreshCw className="h-4 w-4" />Try again</Button>} /> : !data?.driver || !["approved", "ready", "active"].includes(data.driver.status) ? <DriverApplication data={data || {}} reload={load} /> : <><LiveLocation data={data} />{safe === "home" && <DriverHome data={data} reload={load} onOffer={offer} />}{safe === "jobs" && <Jobs data={data} offer={offer} />}{safe === "active" && <ActiveJob data={data} reload={load} />}{safe === "earnings" && <Earnings data={data} reload={load} />}{safe === "history" && <HistoryView data={data} />}{safe === "notifications" && <NotificationCenter workspace="driver" title="Driver notifications" description="Application reviews, delivery offers, payout updates and Driver account activity." />}{safe === "support" && <Support data={data} />}{safe === "profile" && <Profile data={data} />}</>}</div></PortalShell></AuthGate>;
}
